project_id = "nwxdrktahcbxedimxljh"

[functions.cancel-subscription]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.validate-property-limit]
verify_jwt = true

[functions.send-welcome-email]
verify_jwt = false

[functions.send-payment-confirmation]
verify_jwt = false

[functions.send-lead-notification]
verify_jwt = false
