// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nwxdrktahcbxedimxljh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53eGRya3RhaGNieGVkaW14bGpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0NDI0OTMsImV4cCI6MjA3MzAxODQ5M30.3Jy31ppFyAElstAdft3mGR9MlEDSKvJ5TRNKTZtmbf0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});